routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('frontend.home.index');
});*/

Auth::routes();

//Route::get('frontend/home/index', 'HomeController@index')->name('/');
Route::get('/', 'HomeController@index');
Route::post('register-user', 'Frontend\UserController@register')->name('user.register');

Route::post('/','Frontend\BookController@search')->name('book.search');
Route::get('category-search','Frontend\BookController@searchByCategory')->name('category.search');

Route::get('authors-search','Frontend\BookController@searchByAuthor')->name('author.search');
Route::get('narrator-search','Frontend\BookController@searchByNarrator')->name('narrator.search');
Route::get('publisher-search','Frontend\BookController@searchByPublisher')->name('publisher.search');


Route::get('book/{id}','Frontend\BookController@book')->name('book');
Route::post('add-comment/{id}','Frontend\BookController@addComment')->name('add.comment');

Route::group(['middleware'=>'auth'],function (){

    Route::get('add','Frontend\CartController@add')->name('add');
    Route::get('cart','Frontend\CartController@index');

    Route::post('/remove-item/{id}', 'Frontend\CartController@removeItem')->name('cart.remove');

    Route::get('order-verify','Frontend\OrderController@verify')->name('order.verify');
    Route::get('payment-verify/{id}','Frontend\PaymentController@verify')->name('payment.verify');
    Route::get('credit','Frontend\CreditController@index')->name('credit');
    Route::PATCH('credit-verify/{id}','Frontend\CreditController@verify')->name('credit.verify');

    Route::resource('profile','Frontend\ProfileController');
    Route::PATCH('profile-rename/{id}','Frontend\ProfileController@rename')->name('rename');




});

Route::group(['middleware' => ['admin']], function(){
    Route::prefix('admin/')->group(function (){
        Route::get('/', 'HomeController@admin')->middleware('admin')->name('admin');

        Route::resource('/categories', 'Admin\CategoryController');

        Route::resource('photos','Admin\PhotoController');
        Route::post('photos/upload','Admin\PhotoController@upload')->name('photos.upload');
        Route::post('photos/slideUpload','Admin\PhotoController@slideUpload')->name('photos.slideUpload');

        Route::resource('voices','Admin\VoiceController');
        Route::post('voices/upload','Admin\VoiceController@upload')->name('voices.upload');

        Route::resource('books','Admin\BookController');
        Route::resource('subscriptions','Admin\SubscriptionController');
        Route::resource('publishers','Admin\PublisherController');
        Route::resource('authors','Admin\AuthorController');
        Route::resource('narrators','Admin\NarratorController');
        Route::resource('banks','Admin\BankController');

        Route::get('comments','Admin\CommentController@index')->name('comments.index');
        Route::post('actions/{id}', 'Admin\CommentController@actions')->name('comments.actions');

        Route::delete('comments/{id}', 'Admin\CommentController@destroy')->name('comments.destroy');

        Route::get('orders','Admin\OrderController@index')->name('orders.index');
        Route::resource('users','Admin\UserController');
        Route::resource('sliders','Admin\SliderController');
        Route::resource('settings','Admin\SettingController');

    });

});

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
class Photo extends Model
{
    protected $uploads = '/storage/photos/';
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function getPathAttribute($photo)
    {
        return $this->uploads.$photo;
    }
    public function books()
    {
        return $this->belongsToMany(Book::class);
    }
}

app/Http/Controllers/Frontend/BookController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Author;
use App\Book;
use App\Category;
use App\Comment;
use App\Voice;
use foo\bar;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Mockery\Exception;
use function Sodium\add;
use Validator;

class BookController extends Controller
{
    public function addComment(Request $request)
    {
        $validator=Validator::make($request->all(),[
            'title'=>'required',
            'name'=>'required',
             'description'=>'required',
             'email'=>'required',
        ],[
            'title.required'=>'موضوع خود را وارد کنید',
            'name.required'=>' نام خود را وارد کنید',
            'description.required'=>'متن خود را وارد کنید',
            'email.required'=>'ایمیل خود را وارد کنید',

        ]);
        if($validator->fails()){
            return back()->withErrors($validator)->withInput();
        }
        else {
            $newComment = new Comment();
            $newComment->title = $request->input('title');
            $newComment->description = $request->input('description');
            $newComment->email = $request->input('email');
            $newComment->book_id = $request->id;
            $newComment->status = 0;
            $newComment->name = $request->input('name');
            if (Auth::check()) {
                $newComment->user_id = Auth::user()->id;
            }
            $newComment->save();
            Session::flash('success', 'نظر شما در مورد این کتاب ثبت گردید');
            return back();
        }

    }

    public function search(Request $request)
    {

        $q = $request->input('search');
        $books = Book::with('photos', 'authors')
            ->where('title', 'LIKE', '%' . $q . '%')
            ->where('status',1)
            ->get();
        $categories = Category::with('childrenRecursive')
            ->where('parent_id', null)
            ->get();
        $count = count($categories);
        $categories1 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset(0)
            ->limit($count / 2)->get();
        $categories2 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset($count / 2)
            ->limit($count / 2)->get();
        return view('frontend.search.index', compact(['categories1', 'categories2', 'books','q']));

    }

    public function searchByAuthor(Request $request)
    {

        $books = Book::with('photos', 'authors')->where('author_id', $request->author_id)
            ->where('status',1)
            ->get();
        $categories = Category::with('childrenRecursive')
            ->where('parent_id', null)
            ->get();
        $count = count($categories);
        $categories1 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset(0)
            ->limit($count / 2)->get();
        $categories2 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset($count / 2)
            ->limit($count / 2)->get();
        return view('frontend.search.index', compact(['categories1', 'categories2', 'books']));
    }

    public function searchByNarrator(Request $request)
    {
        $books = Book::with('photos', 'authors')->where('narrator_id', $request->narrator_id)
            ->where('status',1)
            ->get();
        $categories = Category::with('childrenRecursive')
            ->where('parent_id', null)
            ->get();
        $count = count($categories);
        $categories1 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset(0)
            ->limit($count / 2)->get();
        $categories2 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset($count / 2)
            ->limit($count / 2)->get();
        return view('frontend.search.index', compact(['categories1', 'categories2', 'books']));
    }

    public function searchByPublisher(Request $request)
    {
        $books = Book::with('photos', 'authors')->where('publisher_id', $request->publisher_id)
            ->where('status',1)
            ->get();
        $categories = Category::with('childrenRecursive')
            ->where('parent_id', null)
            ->get();
        $count = count($categories);
        $categories1 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset(0)
            ->limit($count / 2)->get();
        $categories2 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset($count / 2)
            ->limit($count / 2)->get();
        return view('frontend.search.index', compact(['categories1', 'categories2', 'books']));
    }

    public function searchByCategory(Request $request)
    {
        $id = $request->id;

        $category = Category::with('childrenRecursive')
            ->where('parent_id', $id)
            ->first();

        if (!isset($category))
            return view('errors.404');

        $books = Book::with('photos', 'authors')->where('category_id', $category->id)
            ->where('status',1)->get();
        $categories = Category::with('childrenRecursive')
            ->where('parent_id', null)
            ->get();
        $count = count($categories);
        $categories1 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset(0)
            ->limit($count / 2)->get();
        $categories2 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset($count / 2)
            ->limit($count / 2)->get();
        return view('frontend.search.index', compact(['categories1', 'categories2', 'books']));

    }


    public function book($id)
    {



        if (Auth::check()) {
            $book = Book::with('photos', 'voices', 'authors', 'publishers', 'narrators', 'comments')->whereId($id)->first();


            $comments = Comment::where([['book_id', $id], ['status', 1]])->get();
            $voices = new Voice();

            $categories = Category::all();
            $count = count($categories);

            $categories1 = Category::with('childrenRecursive')
                ->where('parent_id', null)->offset(0)
                ->limit($count / 2)->get();
            $categories2 = Category::with('childrenRecursive')
                ->where('parent_id', null)->offset($count / 2)
                ->limit($count / 2)->get();
            try {
                $book_purchased = DB::table('orders')
                    ->leftJoin('order__items', 'orders.id', '=', 'order__items.order_id')
                    ->leftJoin('books', 'order__items.book_id', '=', 'books.id')
                    ->select('order__items.*', 'orders.*', 'books.*')
                    ->where('orders.user_id', Auth::user()->id)
                    ->where('orders.status', 1)
                    ->where('books.id', $id)
                    ->get();
            } catch (\Exception $e) {
                return view('errors.404');
            }

            $not_free_voice = [];
            $free_voice[] = [];
            $j = 0;
            $i = 0;
            if (!isset($book->voices)) {
                return view('errors.404');
            }


            if (count($book_purchased) > 0) {
                foreach ($book->voices as $NF_voice) {
                    if ($NF_voice->free == 0) {
                        $not_free_voice[$i] = $NF_voice;
                    }
                    $i++;
                }
            }
            foreach ($book->voices as $F_voice) {
                if ($F_voice->free == 1) {
                    $free_voice[$j] = $F_voice;
                    $j++;
                }
            }


            return view('frontend.books.index', compact(['categories1', 'categories2', 'book', 'voices', 'comments', 'book_purchased', 'not_free_voice', 'free_voice']));
        }
        else{

            $book = Book::with('photos', 'voices', 'authors', 'publishers', 'narrators', 'comments')->whereId($id)->where('status',1)->first();


            $comments = Comment::where([['book_id', $id], ['status', 1]])->get();
            $voices = new Voice();

            $categories = Category::all();
            $count = count($categories);

            $categories1 = Category::with('childrenRecursive')
                ->where('parent_id', null)->offset(0)
                ->limit($count / 2)->get();
            $categories2 = Category::with('childrenRecursive')
                ->where('parent_id', null)->offset($count / 2)
                ->limit($count / 2)->get();
            $free_voice[] = [];
            $j = 0;
            $i = 0;
            if (!isset($book->voices)) {
                return view('errors.404');
            }

            foreach ($book->voices as $F_voice) {
                if ($F_voice->free == 1) {
                    $free_voice[$j] = $F_voice;
                    $j++;
                }
            }
            if (!count($book)==0){
            $visit=$book->visit;
            $d= DB::table('books')->whereId($book->id)->update(['visit' => $visit+1]);
             }
            return view('frontend.books.index', compact(['categories1', 'categories2', 'book', 'voices', 'comments', 'free_voice']));
        }
    }

    public function PurchaseApi($id)
    {
        return $id;
    }
}

app/Http/Controllers/Frontend/CreditController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Book;
use App\Category;
use App\Comment;
use App\Order;
use App\Order_Item;
use App\Payment;
use App\Subscription;
use App\Vip;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CreditController extends Controller
{
    public function index()
    {
        $categories =Category::all();
        $count= count($categories);
        $categories1 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset(0)
            ->limit($count/2)->get();
        $categories2 = Category::with('childrenRecursive')
            ->where('parent_id', null)->offset($count/2)
            ->limit($count/2)->get();

        return view('frontend.credits.index',compact(['categories1','categories2']));
    }

    public function verify(Request $request)
    {
        if (!$request->id){
            return back();
        }
        $id= $request->id;

        $sub= Subscription::whereId($id)->first();


        $order=new Order();
        $order->amount=$sub->price;
        $order->user_id=Auth::user()->id;
        $order->status=0;
        $order->save();
        $orderId=$order->id;

        $newOrder_Item=new Order_Item();
        $newOrder_Item->price=$sub->price;
        $newOrder_Item->qty=1;
        $newOrder_Item->discount_percent=0;
        $newOrder_Item->order_id=$orderId;
        $newOrder_Item->subscription_id=$sub->id;
        $newOrder_Item->save();


        $payment=new Payment($order->amount,$order->id);
        $result=$payment->doPayment();

        if ($result->Status == 100) {
            return redirect()->to('https://sandbox.zarinpal.com/pg/StartPay/'.$result->Authority);
        } else {
            echo'ERR: '.$result->Status;
            return false;
        }

    }
}

app/Http/Controllers/Frontend/OrderController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Book;
use App\Order;
use App\Order_Item;
use App\Payment;
use App\Vip;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class OrderController extends Controller
{
    public function verify()
    {

        if (!Cart::content()){
            return redirect('/');
        }

        $bookId=[];
        $price=0;
        $free=0;
        foreach (Cart::Content() as $cart){
            $price=$cart->price;
            $free=$cart->options->free;
            $bookId[$cart->id]=$cart->qty;
        }


        $order=new Order();

        $order->amount=$price;
        $order->user_id=Auth::user()->id;
        $order->status=0;
        $order->save();
        $orderId=$order->id;

        foreach (Cart::content() as $item)//add order items
        {

            $newOrder_Item=new Order_Item();
            $newOrder_Item->price=$item->price;
            $newOrder_Item->qty=1;
            $newOrder_Item->discount_percent=$item->discount;
            $newOrder_Item->order_id=$orderId;
            $newOrder_Item->book_id=$item->id;
            $newOrder_Item->save();
        }
        if ($price==0){

            $order=Order::findOrFail($orderId);
            $order->status=1;
            $order->save();

            Session::flash('success', 'پرداخت  با موفقیت انجام شد');
            $b=  DB::table('cart_models')->delete();

            Cart::destroy();
            return redirect('/cart');
        }
        else{
            $payment=new Payment($order->amount,$order->id);
            $result=$payment->doPayment();
            if ($result->Status == 100) {
                return redirect()->to('https://sandbox.zarinpal.com/pg/StartPay/'.$result->Authority);
                //change this =>  'https://sandbox.zarinpal.com/pg/StartPay/  to this => 'Location: https://www.zarinpal.com/pg/StartPay/'
            } else {
                Session::flash('error', 'مشکلی در پرداخت بوجود آمد، با پشتیبانی تماس بگیرید');
                return redirect('/');
                //echo'ERR: '.$result->Status;
            }
        }

    }
}

resources/views/frontend/home/index.blade.php
@extends('layouts.master')
@section('title')
    دانلود کتاب صوتی | masneed.com
@endsection
@section('content')
    <header id="home">
        <div class="head-gradiant"></div>
        <div class="headSlider">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                <div class="carousel-inner">
                    @foreach($slider as $photo)
                        <div class="carousel-item @if($first_slide->id==$photo->id)active @endif">
                            <img class="d-block w-100" src="/storage/photos/{{$photo->path}}">
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <!--<div class="matn">
            <div class="titr px-3">
                <h1 class="mt-5"></h1>
                <p class="tagline"></p>
                <div class="py-5">
                </div>
            </div>
        </div>-->
    </header>

    {{--books--}}
    <div class="section light-bg py-4 book-list">
        <div class="container text-center">

            @if(Session::has('success'))
                <div class="alert alert-success">
                    <div>{{session('success')}}</div>
                </div>
            @endif
            @if(Session::has('error'))
                <div class="alert alert-danger">
                    <div>{{session('error')}}</div>
                </div>
            @endif
               {{-- پرفروش ترین--}}
                    @if($ordered_books->count() && count($setting)!=0 && $setting->order==1)
                    <h3>پرفروش ترین ها</h3>
                    <div class="book-gallery owl-carousel time2">
                        @foreach($ordered_books as $book )
                                <a style="text-decoration:none" href="{{route('book',['id'=>$book->id])}}"><img
                                            src="/storage/photos/{{$book->path}}" class="img-fluid">
                                    <div class="text-center pt-2 h4"><p>{{$book->title}}</p>
                                        <p>{{$book->name}}</p></div>
                                </a>
                        @endforeach
                    </div>
                @endif
                {{-- پر بازدید ترین ها--}}
                @if($visited_books->count() && count($setting)!=0 && $setting->visit==1)
                    <h3> پر بازدید ترین ها</h3>
                    <div class="book-gallery owl-carousel time2">
                        @foreach($visited_books as $book)
                            <a style="text-decoration:none" href="{{route('book',['id'=>$book->id])}}"><img
                                        src="/storage/photos/{{$book->path}}" class="img-fluid">
                                <div class="text-center pt-2 h4"><p>{{$book->title}}</p>
                                    <p>{{$book->name}}</p></div>
                            </a>
                        @endforeach
                    </div>
                @endif
                {{-- آخرین کتاب ها--}}
                @if($lasted_add_books->count()&& count($setting)!=0 && $setting->last==1)
                    <h3> آخرین کتاب ها</h3>
                    <div class="book-gallery owl-carousel time2">
                        @foreach($lasted_add_books as $book)
                            <a style="text-decoration:none" href="{{route('book',['id'=>$book->id])}}"><img
                                        src="/storage/photos/{{$book->path}}" class="img-fluid">
                                <div class="text-center pt-2 h4"><p>{{$book->title}}</p>
                                    <p>{{$book->name}}</p></div>
                            </a>
                        @endforeach
                    </div>
                @endif
                {{--گروه ها--}}
            @foreach($all_category as $category)
                    @foreach($category_books as $book)
                        <h3  @if($book->category_id!=$category->id) style="display: none" @endif>{{$category->title}}</h3>
                        <div class="book-gallery owl-carousel time2" @if($book->category_id!=$category->id) style="display: none" @endif>
                        @if($category->id == $book->category_id )
                            <a style="text-decoration:none" href="{{route('book',['id'=>$book->id])}}"><img
                                        src="/storage/photos/{{$book->path}}" class="img-fluid">
                                <div class="text-center pt-2 h4"><p>{{$book->title}}</p>
                                    <p>{{$book->name}}</p></div>
                            </a>
                        @endif
                    @endforeach
                </div>
            @endforeach
            <div class="section-title mb-1 ">
            </div>
        </div>
    </div>

    {{--Comments --}}
    <div class="section light-bg pt-5" id="personal" @if(!$comments->count()) style="display: none" @endif>
        <div class="container">
            <div class="section-title">
                <h3>آنچه مشتریان ما می گویند</h3>
            </div>
            <div class="row">
                <div class="col-12 col-lg-4  mb-0 mb-md-2">
                    <div class="card features">
                        <div class="card-body">
                            <div class="media">
                                <img class="profile pl-2" src="/frontend/images/profile2.png" alt="">
                                <div class="media-body">
                                    @foreach($comments as $comment)
                                        <div class="card-title"><h4>{{$comment->name}}</h4></div>
                                        <div class="card-text">{{$comment->description}}</div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{--Subscription(planes)--}}
    <div class="section pt-5" id="panels">
        <div class="container">
            <div class="section-title">
                <h3>ارتقاء به اکانت ویژه</h3>
            </div>
            <div class="card-deck">
                @foreach($subscriptions as $subscription)
                    <div class="card panels">
                        <div class="card-header">
                            <h3>{{$subscription->title}}</h3>
                        </div>
                        <ul class="info-panel">
                            <li class="infos">   {{$subscription->limited_book}} کتاب رایگان</li>
                        </ul>
                        <form method="post" action="{{ route('credit.verify', $subscription) }}" accept-charset="UTF-8">
                            @csrf
                            <input type="hidden" name="_method" value="PATCH">
                            <div class="card-body">
                                <button class="btn btn-primary btn-lg btn-block" type="submit">{{$subscription->price}}
                                    تومان
                                </button>
                            </div>
                        </form>
                    </div>
                @endforeach
            </div>
        </div>
    </div>

    <div class="section bg-gradiant download">
        <div class="container">
            <div class="section-title">
                <div class="box-icon"><span class="ti-announcement ti-3x gradiant-icon"></span></div>
                <h3 class="download-title">همکاری با ما</h3>
                <a href="#">
                    <button class="btn btn-light">اطلاعات بیشتر<span><img class="icon-store"
                                                                          src="/frontend/images/Handshake.png"
                                                                          alt=""></span></button>
                </a>
                <p>
                    <small><i>با همکاری در فروش کسب درآمد کنید</i></small>
                </p>
            </div>
        </div>
    </div>
@endsection