routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('frontend.home.index');
});*/

Auth::routes();

//Route::get('frontend/home/index', 'HomeController@index')->name('/');
Route::get('/', 'HomeController@index');
Route::post('register-user', 'Frontend\UserController@register')->name('user.register');

Route::post('/','Frontend\BookController@search')->name('book.search');
Route::get('category-search','Frontend\BookController@searchByCategory')->name('category.search');

Route::get('authors-search','Frontend\BookController@searchByAuthor')->name('author.search');
Route::get('narrator-search','Frontend\BookController@searchByNarrator')->name('narrator.search');
Route::get('publisher-search','Frontend\BookController@searchByPublisher')->name('publisher.search');


Route::get('book/{id}','Frontend\BookController@book')->name('book');
Route::post('add-comment/{id}','Frontend\BookController@addComment')->name('add.comment');

Route::group(['middleware'=>'auth'],function (){

    Route::get('add','Frontend\CartController@add')->name('add');
    Route::get('cart','Frontend\CartController@index');

    Route::post('/remove-item/{id}', 'Frontend\CartController@removeItem')->name('cart.remove');

    Route::get('order-verify','Frontend\OrderController@verify')->name('order.verify');
    Route::get('payment-verify/{id}','Frontend\PaymentController@verify')->name('payment.verify');
    Route::get('credit','Frontend\CreditController@index')->name('credit');
    Route::PATCH('credit-verify/{id}','Frontend\CreditController@verify')->name('credit.verify');

    Route::resource('profile','Frontend\ProfileController');
    Route::PATCH('profile-rename/{id}','Frontend\ProfileController@rename')->name('rename');




});

Route::group(['middleware' => ['admin']], function(){
    Route::prefix('admin/')->group(function (){
        Route::get('/', 'HomeController@admin')->middleware('admin')->name('admin');

        Route::resource('/categories', 'Admin\CategoryController');

        Route::resource('photos','Admin\PhotoController');
        Route::post('photos/upload','Admin\PhotoController@upload')->name('photos.upload');
        Route::post('photos/slideUpload','Admin\PhotoController@slideUpload')->name('photos.slideUpload');

        Route::resource('voices','Admin\VoiceController');
        Route::post('voices/upload','Admin\VoiceController@upload')->name('voices.upload');

        Route::resource('books','Admin\BookController');
        Route::resource('subscriptions','Admin\SubscriptionController');
        Route::resource('publishers','Admin\PublisherController');
        Route::resource('authors','Admin\AuthorController');
        Route::resource('narrators','Admin\NarratorController');
        Route::resource('banks','Admin\BankController');

        Route::get('comments','Admin\CommentController@index')->name('comments.index');
        Route::post('actions/{id}', 'Admin\CommentController@actions')->name('comments.actions');

        Route::delete('comments/{id}', 'Admin\CommentController@destroy')->name('comments.destroy');

        Route::get('orders','Admin\OrderController@index')->name('orders.index');
        Route::resource('users','Admin\UserController');
        Route::resource('sliders','Admin\SliderController');
        Route::resource('settings','Admin\SettingController');

    });

});

resources/views/admin/partials/category.blade.php
@if(isset($selected_category))
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}" @if($selected_category->parent_id==$sub_category->id) selected @endIf>{{str_repeat(' --- ',$level)}}{{$sub_category->title}}</option>
        @if(count($sub_category->childrenRecursive)>0)
            @include('admin.partials.category',['categories'=>$sub_category->childrenRecursive,'level'=>$level+1,'selected_category'])
        @endif
    @endforeach
@else
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}">{{str_repeat(' --- ',$level)}}{{$sub_category->title}}</option>
        @if(count($sub_category->childrenRecursive)>0)
            @include('admin.partials.category',['categories'=>$sub_category->childrenRecursive,'level'=>$level+1])
        @endif
    @endforeach
@endif

resources/views/admin/partials/category_list.blade.php
@foreach($categories as $sub_category)
    <tr>
        <td class="text-center">{{$sub_category->id}}</td>
        <td class="text-right">{{str_repeat(' --- ',$level)}}{{$sub_category->title}}</td>
        @if($sub_category->first_page==1)
            <td><span class="label label-success"> نمایش داده شود</span></td>
        @else
            <td><span class="label label-danger">نمایش داده نشود</span></td>
        @endif
        <td class="text-center">
            <div class="display-inline-block">
                <form method="post" action="/admin/categories/{{$sub_category->id}}">
                    <a href="{{route('categories.edit',$sub_category->id,compact($categories))}}" class="btn btn-warning" >ویرایش</a>
                    @csrf
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit"  class="btn btn-danger " >حذف</button>
                </form>
            </div>

        </td>
    </tr>
    @if(count($sub_category->childrenRecursive)>0)
        @include('admin.partials.category_list',['categories'=>$sub_category->childrenRecursive,'level'=>$level+1])
    @endif
@endforeach

resources/views/admin/partials/edit_book_category.blade.php
@if(isset($selected_category))
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}" @if($selected_category->id==$sub_category->id) selected @endIf>{{str_repeat(' --- ',$level)}}{{$sub_category->title}}</option>
        @if(count($sub_category->childrenRecursive)>0)
            @include('admin.partials.edit_book_category',['categories'=>$sub_category->childrenRecursive,'level'=>$level+1,'selected_category'])
        @endif
    @endforeach
@else
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}">{{str_repeat(' --- ',$level)}}{{$sub_category->title}}</option>
        @if(count($sub_category->childrenRecursive)>0)
            @include('admin.partials.edit_book_category',['categories'=>$sub_category->childrenRecursive,'level'=>$level+1])
        @endif
    @endforeach
@endif

resources/views/admin/partials/form-errors.blade.php
@if(count($errors)>0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif